name: Build neutralino binaries

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm i -g @neutralinojs/neu
      - run: which neu
      - run: neu update 
      - run: neu build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Mart-build
          path: dist/Mart/*
